# np.save()

The numpy.save() function is used to save a single NumPy array to a binary file in NumPy's .npy format. This format is efficient for storing and loading NumPy arrays. [1]  

Syntax:

`numpy.save(file, arr, allow_pickle=True, fix_imports=True)`

Parameters: 

- file: This can be a file-like object or a string representing the filename. If it's a string, a .npy extension will be appended if it's not already present. 
- arr: The array-like object (e.g., a NumPy array) to be saved. 
- allow_pickle: (Optional, default is True) Allows saving of object arrays using Python's pickle serialization. 
- fix_imports: (Optional, default is True) Used when allow_pickle is True to remap old module names to new ones during pickling for compatibility. 

Example: 

In [9]:
import numpy as np
import pandas as pd
## Create a NumPy array
my_array = np.array([[1, 2, 3], [4, 5, 6]])

# Save the array to a file named 'my_data.npy'
np.save('my_data.npy', my_array)

# To load the array later:
loaded_array = np.load('my_data.npy')
print(loaded_array)

[[1 2 3]
 [4 5 6]]


For saving multiple arrays into a single file, numpy.savez() or numpy.savez_compressed() can be used, which create .npz files (zipped archives containing individual .npy files). 

AI responses may include mistakes.

[1] https://www.quora.com/How-do-you-save-a-NumPy-array-as-a-file

## np.savetxt()

To save a NumPy array in a text format (with a .txt or .csv extension), use numpy.savetxt:

In [ ]:
import numpy as np 
 
# Create a NumPy array 
array = np.array([[1, 2, 3], [4, 5, 6]]) 
 
# Save the array to a text file 
np.savetxt('my_array.txt', array) 
np.savetxt('my_array.csv', array, delimiter=',') 


# Loading the Text File

# To load the array back from a text file, use numpy.loadtxt:

loaded_array = np.loadtxt('my_array.txt', dtype=np.int32) 

In [25]:
loaded_array.astype(np.int32)
loaded_array

array([[1., 2., 3.],
       [4., 5., 6.]])

In [24]:
!cat my_array.txt

1.000000000000000000e+00 2.000000000000000000e+00 3.000000000000000000e+00
4.000000000000000000e+00 5.000000000000000000e+00 6.000000000000000000e+00


In [17]:
!cat my_array.csv

1.000000000000000000e+00,2.000000000000000000e+00,3.000000000000000000e+00
4.000000000000000000e+00,5.000000000000000000e+00,6.000000000000000000e+00


In [18]:
df = pd.DataFrame(loaded_array)
df

0    1    2
0  1.0  2.0  3.0
1  4.0  5.0  6.0

In [12]:
arr.array([[1. 2. 3.]
 [4. 5. 6.]])

SyntaxError: invalid syntax. Perhaps you forgot a comma? (1888476486.py, line 1)

Summary

Use np.save for binary files (.npy).
Use np.savetxt for text files (.txt or .csv).
These methods allow you to easily save and load NumPy arrays for later use.